services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_BOT_CLIENT_ID=${DISCORD_BOT_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DOMAIN=${DOMAIN}
      - REQUESTBIN_SERVICE_URL=http://requestbin:3000
      - REVSHELL_HTTP_BASE_URL=http://revshell-session.taildb374e.ts.net:8000
      - REVSHELL_TCP_HOST=revshell-session.taildb374e.ts.net
      - REVSHELL_TCP_PORT=3000
  requestbin:
    build:
      context: ./requestbin
      dockerfile: Dockerfile
    environment:
      - DOMAIN=${DOMAIN}
    expose:
      - 3000
  requestbin-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - requestbin
    environment:
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    command: tunnel --no-autoupdate run --token ${REQBIN_TUNNEL_TOKEN}
