services:
  revshell:
    build:
      context: ./revshell
      dockerfile: Dockerfile
    environment:
      - DOMAIN=${DOMAIN}
      - HTTP_PORT=${REVSHELL_HTTP_PORT:-8000}
      - REVSHELL_LISTEN_PORT=${REVSHELL_TCP_PORT:-3000}
    ports:
      - "${REVSHELL_HTTP_PORT:-8000}:8000"
      - "${REVSHELL_TCP_PORT:-3000}:3000"
    restart: unless-stopped
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - revshell
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_BOT_CLIENT_ID=${DISCORD_BOT_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DOMAIN=${DOMAIN}
      - REQUESTBIN_SERVICE_URL=${REQUESTBIN_SERVICE_URL}
      - REVSHELL_HTTP_BASE_URL=${REVSHELL_HTTP_BASE_URL}
      - REVSHELL_TCP_HOST=${REVSHELL_TCP_HOST}
      - REVSHELL_TCP_PORT=${REVSHELL_TCP_PORT}
  requestbin:
    build:
      context: ./requestbin
      dockerfile: Dockerfile
    environment:
      - DOMAIN=${DOMAIN}
    expose:
      - 3000
  requestbin-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - requestbin
    environment:
      - TUNNEL_TRANSPORT_PROTOCOL=http2
    command: tunnel --no-autoupdate run --token ${REVSHELL_TUNNEL_TOKEN}