name: Deploy to dev

on:
    push:
        branches: [develop]

jobs:
    deploy:
        runs-on: [self-hosted, tafka-deploy-master]
        environment: develop
        concurrency:
            group: tafka-deploy-master
            cancel-in-progress: true

        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: private key permissions
              run: |
                  mkdir -p /tmp/
                  echo "${{ secrets.DEV_TEST_SSH_KEY }}" > /tmp/key
                  chmod 600 /tmp/key

            - name: Rsync manually
              run: |
                  rsync -avz --delete --exclude='.git' --exclude='.env' --exclude='nginx/ssl' -e "ssh -i /tmp/key" ./ ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }}:/opt/app/CTF-Bot/

            - name: Create .env file on remote
              run: |
                  ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} 'echo "${{ secrets.ENV_FILE_DEV }}" | base64 -d > /opt/app/CTF-Bot/.env'

            - name: Run deploy.sh remotely
              run: |
                  ssh -i /tmp/key ${{ secrets.DEV_TEST_USER }}@${{ secrets.DEV_TEST_HOST }} "chmod +x /opt/app/CTF-Bot/deploy.sh && cd /opt/app/CTF-Bot && sudo ./deploy.sh"

            - name: Remove ssh key
              run: rm /tmp/key
